<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>PokerCalculator</RootNamespace>
    <AssemblyName>PokerCalculator</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PokerCalculator.Core\**" />
    <EmbeddedResource Remove="PokerCalculator.Core\**" />
    <None Remove="PokerCalculator.Core\**" />
    <Compile Remove="PokerCalculator.Api\**" />
    <EmbeddedResource Remove="PokerCalculator.Api\**" />
    <None Remove="PokerCalculator.Api\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="PokerCalculator.Core\PokerCalculator.Core.csproj" />
  </ItemGroup>

</Project>
